# Generated by Django 4.2 on 2025-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_department_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="coaching_category",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("soft_skills", "Soft Skills"),
                    ("leadership", "Leadership"),
                ],
                default="technical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="membership_type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium"), ("vip", "VIP")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
