# Generated by Django 4.2 on 2025-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee",
            "0003_employee_coaching_category_employee_membership_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="coaching_category",
            field=models.CharField(
                choices=[
                    ("Technical", "Technical"),
                    ("Soft Skills", "Soft Skills"),
                    ("Leadership", "Leadership"),
                ],
                default="Technical",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("HR", "Human Resources"),
                    ("IT", "Information Technology"),
                    ("FIN", "Finance"),
                    ("MKT", "Marketing"),
                    ("OPS", "Operations"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic"),
                    ("Premium", "Premium"),
                    ("Elite", "Elite"),
                ],
                default="Basic",
                max_length=20,
            ),
        ),
    ]
