# Generated by Django 4.2 on 2025-05-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_coaching_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_no",
            field=models.CharField(default="TEMP001", max_length=5),
        ),
    ]
