# Generated by Django 4.2 on 2025-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_alter_employee_emp_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_no",
            field=models.CharField(max_length=5),
        ),
    ]
